micronaut:
  application:
    name: myorganization

  server:
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - http://localhost:3000
            - https://amitak-1598.github.io
            - https://dashboard.amitak.xyz
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization
            - Accept
            - Origin
            - X-Requested-With
            - Access-Control-Request-Method
            - Access-Control-Request-Headers

netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    dialect: MYSQL
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Amit@123
    schema-generate: none
    url: jdbc:mysql://localhost:3306/idb?useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: amit

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

jackson:
  serializationInclusion: ALWAYS
